#README
#Line 27 replace email_address with email address
#Line 30 replace password with password
#Change "message to send" in line 105 to the message to send N.B: go to next line of message with \n 
 
import time
 
from selenium import webdriver
from selenium.common.exceptions import UnexpectedAlertPresentException
from selenium.webdriver.common.keys import Keys
import pandas as pd
 
# driver = webdriver.Firefox(executable_path='<Path>/geckodriver.exe')
# This block of code is used to block the notification popup which is generated by site
options = webdriver.ChromeOptions()
options.add_argument("--disable-notifications")
 
# to open chrome webbrowser and maximize the window
driver = webdriver.Chrome(executable_path="chromedriver.exe", chrome_options=options)
driver.maximize_window()
 
#Implicit Wait when element is taking time to load
driver.implicitly_wait(20)
 
# connect to the specific ip address
driver.get("http://www.facebook.com")
time.sleep(5) 
# Login to Facebook

driver.find_element_by_id("email").send_keys("yourmail")
driver.find_element_by_id("pass").send_keys("yourpassword")
driver.find_element_by_id("loginbutton").click();
 
# Waiting time 
time.sleep(5)
driver.get('https://www.facebook.com/search/posts/?q=%22'+'Search Term'+'%22&epa=SERP_TAB')
"""content = 
for lek in content:
    leky = lek.get_attribute("href")
    print(leky)"""
# Click on Profile Name

listProfileName = []
LIKES = []
COMMENTS = []
SHARES = []
DATE = []
 
# Flag to check the visibility of 'Films' Section (this section's placing is just after the friend list)
movieSection = False
 
# Loop to check the 'Films' Section  in each iteration

# Get the list of all friends
#profilePicList = driver.find_elements_by_css_selector('a._7gyi')
profilePicList = driver.find_elements_by_partial_link_text('20')
for profilePic in profilePicList:
    # Get the profile URL of friend in each iteration of the loop by using 'href' attribute
    profileURL = profilePic.get_attribute("href")

    # Append the list by the profile name
    listProfileName.append(profileURL)

# Press Control + END to get the invisible friend on the current visible portion on the page
#profilePicList[len(profilePicList) - 1].send_keys(Keys.CONTROL + " " + Keys.END);
 
# Then we have added the filtered list by using 'Set' [REmove all duplicate name]
filteredFriendSet = set(listProfileName)
LINKS = list(filteredFriendSet)

for such in LINKS:
    driver.get(such)
    try:
        reactions = driver.find_element_by_css_selector('span._81hb').text
        LIKES.append(reactions)
    except:
        LIKES.append("no like")
    try:
        comments = driver.find_element_by_partial_link_text('omments').text
        COMMENTS.append(comments)
    except:
        COMMENTS.append("no comment")
    try:
        shares = driver.find_element_by_partial_link_text('hares').text
        SHARES.append(shares)
    except:
        SHARES.append("no share")
    try:
        date = driver.find_element_by_css_selector('span._6-cm').text
        DATE.append(date)
    except:
        DATE.append("no date")
        
DF = pd.DataFrame({'Related Posts': LINKS,
                   'Likes Count':LIKES,
                   'Comments Count': COMMENTS,
                   'Shares Count': SHARES,
                   'Date Published': DATE,
                   })  #defines columns for storing the Names and H-index using pandas.
DF.to_csv('facebook3.csv') #specifies the name of the csv file"""
