# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NC5k4CmrUhihDLYkQgiRyf0YSpxlLoz2
"""

from grammarbot import GrammarBotClient
import spacy
nlp = spacy.load('en')

text = input("Enter the body of the message: ")
tokens = nlp(text)
count = 0
for sent in tokens.sents:
    x = sent.string.strip()
    #print(x)
    client = GrammarBotClient()
    res = client.check(x, 'en-GB')
    if len(res.matches) > 0:
      #print(res.matches)
      count += 1
if count > 5:
  print("\n\nThis job is probably fake")